### PR TITLE
Enhanced tooltip + format number refactor

### PR DESCRIPTION
**Pull request by anguila**
- Enhanced tooltip
- Function refactor (So it'll be easier to add new currencies and
  format)

### CODE REVIEW

**Comment by xavierlp** [comment]
Hello anguila

I just commit your update on Tootip

I could not find the function refactor ...

Thanks again

**Comment by anguila** [comment]
Hi Xaver,
I'm talking about formatNumber(). Instead of formatting every time i just created a function and I'm calling it when needed.

Btw, instead of using this function, I think its better if you use the .qText value stored in the hypercube measure, so then you leave the formatting to the end user in Qlik. So you take the .qValue for calculation but .qText for popup.

Cheers,

**Comment by xavierlp** [comment]
Hi David

It is a good idea, but I could not to implement it.
For somes nodes we have sum, and so I had to reformat the result....

2016-08-16 22:42 GMT+02:00 David Alcobero notifications@github.com:

**Comment by xavierlp** [comment]
include in the current version

**Pull request closed without merging**
